version: '3.3'
# Multi-host setup for behat tests

services:
  web:
    command: /bin/bash -c "cd /var/www && cp -a doc/nginx/ez_params.d /etc/nginx && bin/vhost.sh --host-name=site.example.com --host-alias='*.local admin.example.com test.example.com' --template-file=doc/nginx/vhost.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      frontend:
        aliases:
        # Multihost aliases
          - site.example.com
          - admin.example.com
          - test.example.com
        # SiteFactory aliases
          - test0.local
          - test1.local
          - test2.local
          - test3.local
          - test4.local
          - test5.local
          - test6.local
          - test7.local
          - test8.local
          - test9.local
      backend:
        aliases:
        # Multihost aliases
          - site.example.com
          - admin.example.com
          - test.example.com
        # SiteFactory aliases
          - test0.local
          - test1.local
          - test2.local
          - test3.local
          - test4.local
          - test5.local
          - test6.local
          - test7.local
          - test8.local
          - test9.local
