version: '3.3'
# Appends services to prod.yml, prod+dev, prod+redis, ..., always latest

services:
  selenium:
    image: ${SELENIUM_IMAGE}
    ports:
     - "9999:9999"
     - "7900:7900"
     - "4444:4444"
     - "5900:5900"
    environment:
     - SE_VNC_NO_PASSWORD=1
     - SE_NODE_MAX_SESSIONS=2
     - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    networks:
     - backend
    # Because of: https://github.com/elgalu/docker-selenium/issues/20
    shm_size: '2gb'

  app:
    depends_on:
     - selenium
    environment:
     - EZP_TEST_REST_HOST=$WEB_HOST
     - BEHAT_SELENIUM_HOST=$SELENIUM_HOST
     - SELENIUM_HOST=$SELENIUM_HOST
     - BEHAT_WEB_HOST=$WEB_HOST
     - WEB_HOST=$WEB_HOST
     - CLOUDINARY_URL
